import { Tool } from "@/types";

export const tools: Tool[] = [
  // FINANÇAS
  {
    slug: "juros-compostos",
    name: "Juros Compostos",
    description: "Calcule juros compostos e veja o crescimento do seu dinheiro ao longo do tempo",
    category: "financas",
    keywords: ["juros compostos", "investimento", "rendimento", "capital", "montante"],
    popular: true,
  },
  {
    slug: "juros-simples",
    name: "Juros Simples",
    description: "Calcule juros simples sobre um capital inicial em um período determinado",
    category: "financas",
    keywords: ["juros simples", "empréstimo", "rendimento", "capital"],
  },
  {
    slug: "simulador-investimentos",
    name: "Simulador de Investimentos",
    description: "Simule diferentes cenários de investimento e compare rendimentos",
    category: "financas",
    keywords: ["investimento", "simulação", "CDB", "tesouro direto", "renda fixa"],
    popular: true,
  },
  {
    slug: "financiamento",
    name: "Calculadora de Financiamento",
    description: "Calcule parcelas e total a pagar em um financiamento pelo sistema SAC ou PRICE",
    category: "financas",
    keywords: ["financiamento", "parcela", "SAC", "PRICE", "imóvel", "carro"],
  },
  {
    slug: "emprestimo",
    name: "Calculadora de Empréstimo",
    description: "Descubra o custo total de um empréstimo e compare diferentes opções",
    category: "financas",
    keywords: ["empréstimo", "parcela", "taxa", "crédito"],
  },
  {
    slug: "salario-liquido",
    name: "Calculadora de Salário Líquido",
    description: "Calcule seu salário líquido após descontos de INSS, IRRF e outros",
    category: "financas",
    keywords: ["salário líquido", "INSS", "IRRF", "desconto", "holerite"],
    popular: true,
  },
  {
    slug: "decimo-terceiro",
    name: "Calculadora de 13º Salário",
    description: "Calcule o valor do décimo terceiro salário e os descontos aplicáveis",
    category: "financas",
    keywords: ["décimo terceiro", "13 salário", "natal", "gratificação"],
  },
  {
    slug: "ferias",
    name: "Calculadora de Férias",
    description: "Calcule o valor das suas férias com 1/3 constitucional e descontos",
    category: "financas",
    keywords: ["férias", "1/3", "adicional", "descanso"],
  },
  {
    slug: "rescisao",
    name: "Calculadora de Rescisão",
    description: "Calcule todos os valores da rescisão contratual de trabalho",
    category: "financas",
    keywords: ["rescisão", "demissão", "aviso prévio", "FGTS", "trabalhista"],
  },
  {
    slug: "inss",
    name: "Calculadora de INSS",
    description: "Calcule a contribuição ao INSS baseada no seu salário",
    category: "financas",
    keywords: ["INSS", "previdência", "contribuição", "aposentadoria"],
  },
  {
    slug: "margem-lucro",
    name: "Calculadora de Margem de Lucro",
    description: "Calcule a margem de lucro bruta e líquida do seu negócio",
    category: "financas",
    keywords: ["margem de lucro", "lucratividade", "receita", "custo"],
  },
  {
    slug: "markup",
    name: "Calculadora de Markup",
    description: "Calcule o markup ideal para precificação dos seus produtos ou serviços",
    category: "financas",
    keywords: ["markup", "precificação", "preço de venda", "margem"],
  },
  {
    slug: "roi",
    name: "Calculadora de ROI",
    description: "Calcule o Retorno sobre Investimento (ROI) de qualquer projeto ou campanha",
    category: "financas",
    keywords: ["ROI", "retorno sobre investimento", "rentabilidade", "lucro"],
  },
  {
    slug: "cac",
    name: "Calculadora de CAC",
    description: "Calcule o Custo de Aquisição de Cliente (CAC) do seu negócio",
    category: "financas",
    keywords: ["CAC", "custo de aquisição", "marketing", "cliente"],
  },
  {
    slug: "ticket-medio",
    name: "Calculadora de Ticket Médio",
    description: "Calcule o ticket médio e estratégias para aumentá-lo",
    category: "financas",
    keywords: ["ticket médio", "vendas", "receita", "cliente"],
  },
  {
    slug: "taxas-marketplace",
    name: "Calculadora de Taxas Marketplace",
    description: "Calcule as taxas de principais marketplaces como Mercado Livre, Shopee, Amazon",
    category: "financas",
    keywords: ["marketplace", "taxas", "Mercado Livre", "Shopee", "Amazon", "comissão"],
  },
  {
    slug: "taxas-cartao",
    name: "Calculadora de Taxas de Cartão",
    description: "Calcule as taxas de parcelamento e débito em diversas operadoras",
    category: "financas",
    keywords: ["cartão de crédito", "taxa", "parcelamento", "maquininha"],
  },
  {
    slug: "pix",
    name: "Calculadora Pix",
    description: "Calcule o valor líquido a receber via Pix para seu negócio",
    category: "financas",
    keywords: ["Pix", "pagamento", "taxa", "recebimento"],
  },
  {
    slug: "valor-futuro",
    name: "Calculadora de Valor Futuro",
    description: "Calcule o valor futuro de um investimento com aportes periódicos",
    category: "financas",
    keywords: ["valor futuro", "investimento", "aportes", "projeção"],
  },
  {
    slug: "valor-presente",
    name: "Calculadora de Valor Presente",
    description: "Calcule o valor presente de um fluxo de caixa futuro",
    category: "financas",
    keywords: ["valor presente", "VPL", "desconto", "fluxo de caixa"],
  },
  {
    slug: "cagr",
    name: "Calculadora de CAGR",
    description: "Calcule a Taxa de Crescimento Anual Composta (CAGR) de um investimento",
    category: "financas",
    keywords: ["CAGR", "crescimento composto", "taxa anual", "investimento"],
  },
  {
    slug: "rentabilidade",
    name: "Calculadora de Rentabilidade",
    description: "Calcule e compare a rentabilidade de diferentes investimentos",
    category: "financas",
    keywords: ["rentabilidade", "rendimento", "investimento", "comparação"],
  },
  {
    slug: "dividend-yield",
    name: "Calculadora de Dividend Yield",
    description: "Calcule o Dividend Yield de ações e FIIs para sua análise",
    category: "financas",
    keywords: ["dividend yield", "dividendos", "ações", "FII", "renda passiva"],
  },
  {
    slug: "reserva-emergencia",
    name: "Calculadora de Reserva de Emergência",
    description: "Descubra o valor ideal da sua reserva de emergência",
    category: "financas",
    keywords: ["reserva de emergência", "poupança", "segurança financeira"],
  },
  {
    slug: "independencia-financeira",
    name: "Calculadora de Independência Financeira",
    description: "Calcule quanto você precisa investir para atingir a independência financeira",
    category: "financas",
    keywords: ["independência financeira", "aposentadoria", "FIRE", "investimento"],
    popular: true,
  },

  // TEXTO
  {
    slug: "contador-palavras",
    name: "Contador de Palavras",
    description: "Conte palavras, caracteres, linhas e parágrafos no seu texto",
    category: "texto",
    keywords: ["contar palavras", "contador", "texto", "caracteres"],
    popular: true,
  },
  {
    slug: "contador-caracteres",
    name: "Contador de Caracteres",
    description: "Conte caracteres com e sem espaço, perfeito para limites de redes sociais",
    category: "texto",
    keywords: ["contar caracteres", "limite", "Twitter", "Instagram"],
  },
  {
    slug: "remover-espacos",
    name: "Remover Espaços Extras",
    description: "Remova espaços duplos, tabs e espaços desnecessários do texto",
    category: "texto",
    keywords: ["espaços", "limpar", "formatar", "texto"],
  },
  {
    slug: "remover-linhas-vazias",
    name: "Remover Linhas Vazias",
    description: "Elimine linhas em branco e espaços vazios de qualquer texto",
    category: "texto",
    keywords: ["linhas vazias", "limpar", "formatar"],
  },
  {
    slug: "maiusculas",
    name: "Converter para Maiúsculas",
    description: "Converta qualquer texto para letras maiúsculas instantaneamente",
    category: "texto",
    keywords: ["maiúsculas", "uppercase", "converter"],
  },
  {
    slug: "minusculas",
    name: "Converter para Minúsculas",
    description: "Converta qualquer texto para letras minúsculas instantaneamente",
    category: "texto",
    keywords: ["minúsculas", "lowercase", "converter"],
  },
  {
    slug: "capitalizar-texto",
    name: "Capitalizar Texto",
    description: "Capitalize a primeira letra de cada palavra no texto",
    category: "texto",
    keywords: ["capitalizar", "title case", "primeira letra"],
  },
  {
    slug: "inverter-texto",
    name: "Inverter Texto",
    description: "Inverta a ordem dos caracteres ou das palavras do texto",
    category: "texto",
    keywords: ["inverter", "espelhar", "texto"],
  },
  {
    slug: "ordenar-linhas",
    name: "Ordenar Linhas",
    description: "Ordene linhas de texto em ordem alfabética crescente ou decrescente",
    category: "texto",
    keywords: ["ordenar", "alfabético", "linhas", "sort"],
  },
  {
    slug: "remover-duplicados",
    name: "Remover Linhas Duplicadas",
    description: "Remova linhas duplicadas de uma lista ou texto",
    category: "texto",
    keywords: ["duplicados", "linhas únicas", "deduplicar"],
  },
  {
    slug: "lorem-ipsum",
    name: "Gerador Lorem Ipsum",
    description: "Gere texto Lorem Ipsum para mockups e protótipos",
    category: "texto",
    keywords: ["lorem ipsum", "placeholder", "texto fictício", "mockup"],
  },
  {
    slug: "markdown-generator",
    name: "Editor Markdown",
    description: "Editor Markdown com preview em tempo real",
    category: "texto",
    keywords: ["markdown", "editor", "preview", "formatação"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown para HTML",
    description: "Converta Markdown para HTML formatado instantaneamente",
    category: "texto",
    keywords: ["markdown", "html", "converter", "formatação"],
  },
  {
    slug: "html-encode",
    name: "HTML Encode",
    description: "Codifique caracteres especiais em entidades HTML",
    category: "texto",
    keywords: ["HTML encode", "entidades", "escape", "caracteres especiais"],
  },
  {
    slug: "html-decode",
    name: "HTML Decode",
    description: "Decodifique entidades HTML de volta para caracteres normais",
    category: "texto",
    keywords: ["HTML decode", "entidades", "unescape"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Formate e identifique JSON de forma legível",
    category: "texto",
    keywords: ["JSON", "formatar", "identar", "prettify"],
    popular: true,
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    description: "Valide se um JSON é válido e identifique erros de sintaxe",
    category: "texto",
    keywords: ["JSON", "validar", "syntax", "erro"],
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Formate e identifique XML de forma legível",
    category: "texto",
    keywords: ["XML", "formatar", "identar"],
  },
  {
    slug: "csv-formatter",
    name: "CSV Formatter",
    description: "Formate e visualize dados CSV em tabela",
    category: "texto",
    keywords: ["CSV", "tabela", "dados", "planilha"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Teste expressões regulares em tempo real com highlighting",
    category: "texto",
    keywords: ["regex", "expressão regular", "padrão", "teste"],
  },
  {
    slug: "remover-acentos",
    name: "Remover Acentos",
    description: "Remova acentos e caracteres especiais do texto, convertendo para ASCII puro",
    category: "texto",
    keywords: ["acentos", "diacríticos", "normalizar", "ASCII", "slug"],
  },
  {
    slug: "numero-por-extenso",
    name: "Número por Extenso",
    description: "Converta qualquer número para sua representação por extenso em português",
    category: "texto",
    keywords: ["número por extenso", "escrever número", "valor por extenso", "cheque"],
  },
  {
    slug: "contador-ocorrencias",
    name: "Contador de Ocorrências",
    description: "Conte quantas vezes cada palavra ou termo aparece em um texto",
    category: "texto",
    keywords: ["ocorrências", "frequência", "palavras", "contador", "estatísticas"],
  },

  // CONVERSORES
  {
    slug: "celsius-fahrenheit",
    name: "Celsius para Fahrenheit",
    description: "Converta temperaturas de Celsius para Fahrenheit instantaneamente",
    category: "conversores",
    keywords: ["celsius", "fahrenheit", "temperatura", "converter"],
    popular: true,
  },
  {
    slug: "fahrenheit-celsius",
    name: "Fahrenheit para Celsius",
    description: "Converta temperaturas de Fahrenheit para Celsius",
    category: "conversores",
    keywords: ["fahrenheit", "celsius", "temperatura", "converter"],
  },
  {
    slug: "kg-libras",
    name: "Kg para Libras",
    description: "Converta quilogramas para libras (pounds)",
    category: "conversores",
    keywords: ["kg", "libras", "pounds", "peso", "converter"],
  },
  {
    slug: "libras-kg",
    name: "Libras para Kg",
    description: "Converta libras (pounds) para quilogramas",
    category: "conversores",
    keywords: ["libras", "pounds", "kg", "peso", "converter"],
  },
  {
    slug: "km-milhas",
    name: "Km para Milhas",
    description: "Converta quilômetros para milhas",
    category: "conversores",
    keywords: ["km", "milhas", "miles", "distância", "converter"],
  },
  {
    slug: "milhas-km",
    name: "Milhas para Km",
    description: "Converta milhas para quilômetros",
    category: "conversores",
    keywords: ["milhas", "miles", "km", "distância", "converter"],
  },
  {
    slug: "metros-pes",
    name: "Metros para Pés",
    description: "Converta metros para pés (feet)",
    category: "conversores",
    keywords: ["metros", "pés", "feet", "comprimento", "converter"],
  },
  {
    slug: "polegadas-cm",
    name: "Polegadas para Cm",
    description: "Converta polegadas para centímetros",
    category: "conversores",
    keywords: ["polegadas", "inches", "cm", "centímetros", "converter"],
  },
  {
    slug: "litros-galoes",
    name: "Litros para Galões",
    description: "Converta litros para galões americanos ou imperiais",
    category: "conversores",
    keywords: ["litros", "galões", "gallons", "volume", "converter"],
  },
  {
    slug: "galoes-litros",
    name: "Galões para Litros",
    description: "Converta galões americanos para litros",
    category: "conversores",
    keywords: ["galões", "gallons", "litros", "volume", "converter"],
  },
  {
    slug: "bytes-mb",
    name: "Bytes para MB",
    description: "Converta bytes para megabytes de forma precisa",
    category: "conversores",
    keywords: ["bytes", "megabytes", "MB", "armazenamento", "converter"],
  },
  {
    slug: "mb-gb",
    name: "MB para GB",
    description: "Converta megabytes para gigabytes",
    category: "conversores",
    keywords: ["megabytes", "MB", "gigabytes", "GB", "armazenamento"],
  },
  {
    slug: "gb-tb",
    name: "GB para TB",
    description: "Converta gigabytes para terabytes",
    category: "conversores",
    keywords: ["gigabytes", "GB", "terabytes", "TB", "armazenamento"],
  },
  {
    slug: "horas-minutos",
    name: "Horas para Minutos",
    description: "Converta horas para minutos de forma simples",
    category: "conversores",
    keywords: ["horas", "minutos", "tempo", "converter"],
  },
  {
    slug: "minutos-segundos",
    name: "Minutos para Segundos",
    description: "Converta minutos para segundos",
    category: "conversores",
    keywords: ["minutos", "segundos", "tempo", "converter"],
  },
  {
    slug: "dias-horas",
    name: "Dias para Horas",
    description: "Converta dias para horas e outros múltiplos de tempo",
    category: "conversores",
    keywords: ["dias", "horas", "tempo", "converter"],
  },
  {
    slug: "conversor-fusos",
    name: "Conversor de Fusos Horários",
    description: "Converta horários entre diferentes fusos horários do mundo",
    category: "conversores",
    keywords: ["fuso horário", "timezone", "UTC", "horário mundial"],
    popular: true,
  },
  {
    slug: "conversor-tempo",
    name: "Conversor de Tempo",
    description: "Converta entre todas as unidades de tempo: segundos, minutos, horas, dias",
    category: "conversores",
    keywords: ["tempo", "segundos", "minutos", "horas", "dias", "semanas"],
  },
  {
    slug: "conversor-moedas",
    name: "Conversor de Moedas",
    description: "Converta valores entre as principais moedas do mundo",
    category: "conversores",
    keywords: ["moeda", "câmbio", "dólar", "euro", "real", "converter"],
    popular: true,
  },

  // ESTUDOS
  {
    slug: "regra-de-tres",
    name: "Regra de Três",
    description: "Resolva problemas de regra de três simples e composta",
    category: "estudos",
    keywords: ["regra de três", "proporção", "matemática"],
    popular: true,
  },
  {
    slug: "equacao-segundo-grau",
    name: "Equação do 2º Grau",
    description: "Resolva equações do segundo grau com Bhaskara passo a passo",
    category: "estudos",
    keywords: ["equação segundo grau", "Bhaskara", "delta", "raízes"],
  },
  {
    slug: "mmc",
    name: "MMC - Mínimo Múltiplo Comum",
    description: "Calcule o Mínimo Múltiplo Comum entre dois ou mais números",
    category: "estudos",
    keywords: ["MMC", "mínimo múltiplo comum", "múltiplos"],
  },
  {
    slug: "mdc",
    name: "MDC - Máximo Divisor Comum",
    description: "Calcule o Máximo Divisor Comum entre dois ou mais números",
    category: "estudos",
    keywords: ["MDC", "máximo divisor comum", "divisores"],
  },
  {
    slug: "media-escolar",
    name: "Calculadora de Média Escolar",
    description: "Calcule sua média escolar e saiba se você foi aprovado",
    category: "estudos",
    keywords: ["média escolar", "notas", "aprovado", "reprovado"],
    popular: true,
  },
  {
    slug: "media-ponderada",
    name: "Média Ponderada",
    description: "Calcule a média ponderada com pesos diferentes para cada nota",
    category: "estudos",
    keywords: ["média ponderada", "pesos", "notas", "matemática"],
  },
  {
    slug: "porcentagem",
    name: "Calculadora de Porcentagem",
    description: "Calcule porcentagem, desconto, aumento e variação percentual",
    category: "estudos",
    keywords: ["porcentagem", "percentual", "desconto", "aumento"],
    popular: true,
  },
  {
    slug: "fracoes",
    name: "Calculadora de Frações",
    description: "Some, subtraia, multiplique e divida frações com passos detalhados",
    category: "estudos",
    keywords: ["frações", "fração", "soma", "divisão", "matemática"],
  },
  {
    slug: "conversor-fracoes",
    name: "Conversor de Frações",
    description: "Converta frações para decimais e decimais para frações",
    category: "estudos",
    keywords: ["fração", "decimal", "converter", "número misto"],
  },
  {
    slug: "notacao-cientifica",
    name: "Notação Científica",
    description: "Converta números para notação científica e vice-versa",
    category: "estudos",
    keywords: ["notação científica", "potência", "expoente"],
  },
  {
    slug: "pitagoras",
    name: "Teorema de Pitágoras",
    description: "Calcule lados de triângulos retângulos com o teorema de Pitágoras",
    category: "estudos",
    keywords: ["pitágoras", "triângulo", "hipotenusa", "cateto"],
  },
  {
    slug: "area-triangulo",
    name: "Área do Triângulo",
    description: "Calcule a área de triângulos com base e altura ou pelos lados",
    category: "estudos",
    keywords: ["área triângulo", "base", "altura", "geometria"],
  },
  {
    slug: "area-circulo",
    name: "Área do Círculo",
    description: "Calcule a área e circunferência de círculos",
    category: "estudos",
    keywords: ["área círculo", "raio", "diâmetro", "pi", "geometria"],
  },
  {
    slug: "volume-cubo",
    name: "Volume do Cubo",
    description: "Calcule volume e área superficial de cubos e paralelepípedos",
    category: "estudos",
    keywords: ["volume cubo", "aresta", "geometria espacial"],
  },
  {
    slug: "calculadora-cientifica",
    name: "Calculadora Científica",
    description: "Calculadora científica completa com funções trigonométricas e logaritmos",
    category: "estudos",
    keywords: ["calculadora científica", "trigonometria", "logaritmo", "seno", "cosseno"],
    popular: true,
  },
  {
    slug: "numeros-romanos",
    name: "Conversor de Números Romanos",
    description: "Converta números arábicos para romanos e vice-versa",
    category: "estudos",
    keywords: ["números romanos", "algarismos romanos", "converter", "romano"],
  },
  {
    slug: "fatorar-numero",
    name: "Fatoração de Números",
    description: "Decomponha qualquer número em seus fatores primos com passo a passo",
    category: "estudos",
    keywords: ["fatoração", "fatores primos", "decomposição", "primo"],
  },
  {
    slug: "resto-divisao",
    name: "Resto da Divisão (Módulo)",
    description: "Calcule o resto da divisão (operação módulo) entre dois números",
    category: "estudos",
    keywords: ["módulo", "resto divisão", "mod", "divisão inteira"],
  },

  // CRIADORES
  {
    slug: "gerador-hashtags",
    name: "Gerador de Hashtags",
    description: "Gere hashtags relevantes para Instagram, TikTok e outras redes sociais",
    category: "criadores",
    keywords: ["hashtags", "instagram", "tiktok", "social media", "alcance"],
    popular: true,
  },
  {
    slug: "gerador-bio-instagram",
    name: "Gerador de Bio Instagram",
    description: "Crie uma bio profissional e atrativa para o seu Instagram",
    category: "criadores",
    keywords: ["bio instagram", "perfil", "descrição", "instagram"],
  },
  {
    slug: "gerador-username",
    name: "Gerador de Username",
    description: "Crie nomes de usuário únicos e criativos para redes sociais",
    category: "criadores",
    keywords: ["username", "nome de usuário", "nickname", "apelido"],
  },
  {
    slug: "gerador-nome-canal",
    name: "Gerador de Nome de Canal",
    description: "Crie nomes criativos para canais do YouTube e perfis online",
    category: "criadores",
    keywords: ["nome canal", "youtube", "canal", "marca"],
  },
  {
    slug: "gerador-titulos",
    name: "Gerador de Títulos",
    description: "Crie títulos chamativos para artigos, posts e vídeos",
    category: "criadores",
    keywords: ["títulos", "headline", "copywriting", "clique"],
    popular: true,
  },
  {
    slug: "gerador-cta",
    name: "Gerador de CTA",
    description: "Crie chamadas para ação (CTAs) eficazes para marketing",
    category: "criadores",
    keywords: ["CTA", "call to action", "botão", "conversão", "marketing"],
  },
  {
    slug: "gerador-slogans",
    name: "Gerador de Slogans",
    description: "Crie slogans memoráveis para sua marca ou negócio",
    category: "criadores",
    keywords: ["slogan", "tagline", "marca", "branding"],
  },
  {
    slug: "gerador-descricao-youtube",
    name: "Gerador de Descrição YouTube",
    description: "Crie descrições otimizadas para vídeos do YouTube",
    category: "criadores",
    keywords: ["descrição youtube", "SEO video", "youtube", "tags"],
  },
  {
    slug: "gerador-posts",
    name: "Gerador de Posts",
    description: "Crie posts prontos para redes sociais em segundos",
    category: "criadores",
    keywords: ["posts", "conteúdo", "redes sociais", "legenda"],
  },
  {
    slug: "gerador-ideias-conteudo",
    name: "Gerador de Ideias de Conteúdo",
    description: "Gere ideias criativas de conteúdo para blog, YouTube e redes sociais",
    category: "criadores",
    keywords: ["ideias conteúdo", "pauta", "blog", "youtube", "criatividade"],
  },

  // DOCUMENTOS
  {
    slug: "gerador-cpf",
    name: "Gerador de CPF",
    description: "Gere números de CPF válidos para testes e desenvolvimento",
    category: "documentos",
    keywords: ["CPF", "documento", "gerador", "teste", "cadastro"],
    popular: true,
  },
  {
    slug: "validador-cpf",
    name: "Validador de CPF",
    description: "Valide se um número de CPF é válido verificando os dígitos verificadores",
    category: "documentos",
    keywords: ["CPF", "validar", "verificar", "documento"],
    popular: true,
  },
  {
    slug: "gerador-cnpj",
    name: "Gerador de CNPJ",
    description: "Gere números de CNPJ válidos para testes e desenvolvimento",
    category: "documentos",
    keywords: ["CNPJ", "empresa", "gerador", "teste", "documento"],
    popular: true,
  },
  {
    slug: "validador-cnpj",
    name: "Validador de CNPJ",
    description: "Valide se um número de CNPJ é válido verificando os dígitos verificadores",
    category: "documentos",
    keywords: ["CNPJ", "validar", "verificar", "empresa"],
  },
  {
    slug: "gerador-rg",
    name: "Gerador de RG",
    description: "Gere números de RG para testes e desenvolvimento de sistemas",
    category: "documentos",
    keywords: ["RG", "identidade", "gerador", "documento", "teste"],
  },
  {
    slug: "gerador-cnh",
    name: "Gerador de CNH",
    description: "Gere números de CNH válidos para testes e desenvolvimento",
    category: "documentos",
    keywords: ["CNH", "carteira de motorista", "habilitação", "gerador", "teste"],
  },
  {
    slug: "gerador-pis",
    name: "Gerador de PIS/PASEP",
    description: "Gere números de PIS/PASEP válidos para testes de sistemas",
    category: "documentos",
    keywords: ["PIS", "PASEP", "NIT", "trabalhador", "gerador"],
  },
  {
    slug: "gerador-renavam",
    name: "Gerador de RENAVAM",
    description: "Gere números de RENAVAM válidos para testes de sistemas veiculares",
    category: "documentos",
    keywords: ["RENAVAM", "veículo", "carro", "gerador", "documento"],
  },
  {
    slug: "gerador-placa",
    name: "Gerador de Placa de Veículo",
    description: "Gere placas de veículos no formato antigo (ABC-1234) ou Mercosul (ABC1D23)",
    category: "documentos",
    keywords: ["placa", "veículo", "carro", "Mercosul", "gerador"],
  },
  {
    slug: "gerador-titulo-eleitor",
    name: "Gerador de Título de Eleitor",
    description: "Gere números de título de eleitor válidos para testes",
    category: "documentos",
    keywords: ["título de eleitor", "eleições", "TSE", "gerador", "documento"],
  },
  {
    slug: "gerador-cartao-credito",
    name: "Gerador de Cartão de Crédito",
    description: "Gere números de cartão de crédito válidos (Luhn) para testes de sistemas de pagamento",
    category: "documentos",
    keywords: ["cartão de crédito", "Visa", "Mastercard", "Luhn", "teste", "pagamento"],
  },
  {
    slug: "gerador-pessoas",
    name: "Gerador de Pessoas",
    description: "Gere perfis completos com nome, CPF, RG, data de nascimento, endereço e telefone",
    category: "documentos",
    keywords: ["pessoa", "perfil", "CPF", "RG", "endereço", "gerador", "dados fictícios"],
    popular: true,
  },

  // UTILIDADES
  {
    slug: "gerador-qr-code",
    name: "Gerador de QR Code",
    description: "Crie QR Codes personalizados para links, textos, telefones e e-mails",
    category: "utilidades",
    keywords: ["QR code", "código QR", "link", "compartilhar"],
    popular: true,
  },
  {
    slug: "gerador-senhas",
    name: "Gerador de Senhas",
    description: "Gere senhas fortes e seguras com configurações personalizadas",
    category: "utilidades",
    keywords: ["senha forte", "password", "segurança", "gerador"],
    popular: true,
  },
  {
    slug: "validador-email",
    name: "Validador de Email",
    description: "Valide endereços de e-mail e verifique formatação correta",
    category: "utilidades",
    keywords: ["validar email", "email", "endereço", "formato"],
  },
  {
    slug: "calculadora-idade",
    name: "Calculadora de Idade",
    description: "Calcule sua idade exata em anos, meses e dias",
    category: "utilidades",
    keywords: ["idade", "anos", "aniversário", "data nascimento"],
  },
  {
    slug: "calculadora-datas",
    name: "Calculadora de Datas",
    description: "Calcule a diferença entre datas ou adicione/subtraia dias de uma data",
    category: "utilidades",
    keywords: ["datas", "dias", "diferença", "calendário"],
  },
  {
    slug: "sorteador-numeros",
    name: "Sorteador de Números",
    description: "Sorteie números aleatórios em um intervalo, ideal para rifas e sorteios",
    category: "utilidades",
    keywords: ["sorteio", "aleatório", "rifa", "loteria", "números aleatórios"],
  },
  {
    slug: "gerador-nomes",
    name: "Gerador de Nomes Aleatórios",
    description: "Gere nomes brasileiros aleatórios masculinos, femininos ou mistos",
    category: "utilidades",
    keywords: ["nomes", "nomes aleatórios", "nomes brasileiros", "gerador", "personagem"],
  },
];

export function getToolBySlug(categorySlug: string, toolSlug: string): Tool | undefined {
  return tools.find((t) => t.category === categorySlug && t.slug === toolSlug);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.category === categorySlug);
}

export function getPopularTools(limit = 8): Tool[] {
  return tools.filter((t) => t.popular).slice(0, limit);
}

export function getRecentTools(limit = 8): Tool[] {
  return [...tools].slice(-limit).reverse();
}

export function getRelatedTools(tool: Tool, limit = 4): Tool[] {
  return tools
    .filter((t) => t.category === tool.category && t.slug !== tool.slug)
    .slice(0, limit);
}

export function searchTools(query: string): Tool[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
  );
}
